Swarm: fix graylog deploy (#1517)
* Swarm: fix deploy of graylog

Avoid restarting graylog on every deploy (caused by generating new
passwrd secret in Makefile on every run). We use instead secret that is
already present in repo.config

Explicitly define starting order to `stop_first` to avoid 2 replicas
re-using the same volume and potentially race condition

Avoid crash loop back restarting graylog non stop be limite restart
attempts

Fix bug when `configure-graylog` was running against old replica by
waiting on docker stack deploy to converge all services

Increase graceful shutdown timeout to 2 minutes (default 10 sec) to help
graylog gracefully shutdown its resources

All these things shall fix (or help with) the problem when graylog with this error log
```
2026-09-02 07:48:15,138 ERROR: org.graylog2.bootstrap.preflight.PreflightCheckService - Preflight check failed with error: The journal is already locked by another process. Try running fuser "/usr/share/graylog/data/journal/.lock" to find the PID.
2026-09-02 07:48:15,138 ERROR: org.graylog2.bootstrap.CmdLineTool - Startup error:
org.graylog2.bootstrap.preflight.PreflightCheckException: The journal is already locked by another process. Try running fuser "/usr/share/graylog/data/journal/.lock" to find the PID.
```

* imrpove comment

* Comment on why 1200M instead of 1.2G